/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuleB;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ModuleA.*;
import ModuleB.*;
import ModuleC.*;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jun_y
 */
public class InvoiceList extends javax.swing.JFrame {

    private LinkedList<Customer> custList = new LinkedList<>();
    private ModuleC.SinglyLinkedList<Order> orderList = new SinglyLinkedList<Order>();
    private LinkedList<Invoice> invList = new LinkedList<>();

    private Customer cust = new Customer();
    private ModuleC.Order order = new ModuleC.Order();
    private Invoice selectedInv = new Invoice();
    private Invoice inv = new Invoice();

    /**
     * Creates new form InvoiceUI
     */
    public InvoiceList() {
        initComponents();
        clearTable();
        displayTable();


        /*
        Customer tmp1 = new Customer();
        Order tmp2 = new Order();
        tmp1.setCustId("00000");
        tmp2.setOrder_id("00000");
        inv.setInvoiceID("IV1001");
        inv.setCustomer(tmp1);
        inv.setOrder(tmp2);
        inv.setInvoiceStatus("Paid");
        invList.add(inv);
        saveInv();
         */
        //  dummy data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonView = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search:");

        jButton1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Number", "Customer ID", "Order ID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableList);
        if (jTableList.getColumnModel().getColumnCount() > 0) {
            jTableList.getColumnModel().getColumn(0).setResizable(false);
            jTableList.getColumnModel().getColumn(1).setResizable(false);
            jTableList.getColumnModel().getColumn(2).setResizable(false);
            jTableList.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonView.setText("VIEW");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBack)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonView)
                    .addComponent(jButtonBack))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        InvoiceForm ui = new InvoiceForm(inv);
        ui.setVisible(true);
        ui.setResizable(false);
        ui.setTitle("Invoice " + inv.getInvoiceID() + ".pdf");
        ui.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jTableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableList.getModel();
        int selectedRowIndex = jTableList.getSelectedRow();
        String id = model.getValueAt(selectedRowIndex, 0).toString();
        String cust = model.getValueAt(selectedRowIndex, 1).toString();
        String date = model.getValueAt(selectedRowIndex, 2).toString();
        String status = model.getValueAt(selectedRowIndex, 3).toString();
        Order tmp1 = new Order();
        Customer tmp2 = new Customer();

        
        inv.setInvoiceID(id);
        inv.setInvoiceStatus(status);
        inv.setCustomerID(cust);
        inv.setOrderID(date);


    }//GEN-LAST:event_jTableListMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceList ui = new InvoiceList();
                ui.setVisible(true);
                ui.setTitle("Invoice List");
                ui.setResizable(false);
            
            }
        });
    }

    private void load() {
        try {
            ObjectInputStream oiStream1 = new ObjectInputStream(new FileInputStream("customer.dat"));
            ObjectInputStream oiStream2 = new ObjectInputStream(new FileInputStream("orders.dat"));
            ObjectInputStream oiStream3 = new ObjectInputStream(new FileInputStream("invoice.dat"));

            ArrayList<Customer> tmpCust = new ArrayList<Customer>();
            ArrayList<Order> tmpOrder = new ArrayList<Order>();

            ArrayList<Invoice> tmpInv = new ArrayList<Invoice>();
            tmpCust = (ArrayList) oiStream1.readObject();
            tmpOrder = (ArrayList) oiStream2.readObject();

            tmpInv = (ArrayList) oiStream3.readObject();

            for (int i = 0; i < tmpCust.size(); i++) {
                cust = tmpCust.get(i);
                custList.add(cust);
            }
            for (int j = 0; j < tmpOrder.size(); j++) {
                order = tmpOrder.get(j);
                orderList.add(order);
            }
            for (int k = 0; k < tmpInv.size(); k++) {
                inv = tmpInv.get(k);
                invList.add(inv);
            }

            oiStream1.close();
            oiStream2.close();
            oiStream3.close();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Cannot read from file", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Class not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void save() {
        try {
            ObjectOutputStream ooStream1 = new ObjectOutputStream(new FileOutputStream("invoice.dat"));
            ObjectOutputStream ooStream2 = new ObjectOutputStream(new FileOutputStream("customer.dat"));
            ObjectOutputStream ooStream3 = new ObjectOutputStream(new FileOutputStream("orders.dat"));

            ArrayList tmpInv = new ArrayList();
            ArrayList tmpCust = new ArrayList();
            ArrayList tmpOrder = new ArrayList();

            for (int i = 0; i < invList.getNumberOfEntries(); i++) {
                inv = invList.getEntry(i);
                tmpInv.add(inv);
            }
            for (int j = 0; j < custList.getNumberOfEntries(); j++) {
                cust = custList.getEntry(j);
                tmpCust.add(cust);
            }
            for (int k = 0; k < orderList.getNumberOfEntries(); k++) {
                order = orderList.getEntry(k);
                tmpOrder.add(order);
            }

            ooStream1.writeObject(tmpInv);
            ooStream1.close();
            ooStream2.writeObject(tmpCust);
            ooStream2.close();
            ooStream3.writeObject(tmpOrder);
            ooStream3.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Failed to save", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void displayTable() {

        load();
        DefaultTableModel model = (DefaultTableModel) jTableList.getModel();
        model.setRowCount(0);
        for (int i = 0; i < invList.getNumberOfEntries(); i++) {
            inv = invList.getEntry(i);
            Object[] row = {inv.getInvoiceID(), inv.getCustomerID(), inv.getOrderID(), inv.getInvoiceStatus()};
            model.addRow(row);
        }

        jTableList.setModel(model);

    }

    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) jTableList.getModel();
        custList.clear();
        model.setRowCount(0);
        jTableList.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTableList;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
